### ISSUE TITLE
Slow dev server when using vite-plugin-importer

### ISSUE THREAD

**Issue by JanStevens** [ajuner/vite-plugin-importer#7]
Hi 👋 ,

I'm looking into vite (coming from webpack) and quickly find your plugin to be very helpful for builds. When running the dev server I do notice the following pattern: The server is started, page loads and it refreshes again because of a new dependency being found.

```
12:37:44 PM [vite] new dependencies found: @material-ui/core/esm/CircularProgress, @material-ui/core/esm/Box, updating...
12:37:45 PM [vite] ✨ dependencies updated, reloading page...
12:37:47 PM [vite] new dependencies found: @material-ui/core/esm/Grid, updating...
12:37:48 PM [vite] ✨ dependencies updated, reloading page...
12:37:53 PM [vite] new dependencies found: @material-ui/core/esm/Fade, @material-ui/core/esm/Slide, updating...
12:37:55 PM [vite] ✨ dependencies updated, reloading page...
12:37:58 PM [vite] new dependencies found: @material-ui/core/esm/useMediaQuery, updating...
12:37:59 PM [vite] ✨ dependencies updated, reloading page...
12:38:04 PM [vite] new dependencies found: @material-ui/core/esm/IconButton, updating...
12:38:05 PM [vite] ✨ dependencies updated, reloading page...
12:38:08 PM [vite] new dependencies found: @material-ui/core/esm/Button, updating...
12:38:09 PM [vite] ✨ dependencies updated, reloading page...
```

I have in my config the following
```ts
import tsconfigPaths from 'vite-tsconfig-paths';
...
    pluginImport({
      libraryName: '@material-ui/core',
      libraryDirectory: 'esm',
      camel2DashComponentName: false,
    }),
    pluginImport({
      libraryName: 'lodash-es',
      libraryDirectory: '',
      camel2DashComponentName: false,
    }),
```

**Comment by ajuner** [comment]
Sorry, I can't solve it.Because I use the `transformSync` to process.
You can use `vite-plugin-style-import`

**Comment by Geocld** [comment]
> Hi 👋 ,
> 
> I'm looking into vite (coming from webpack) and quickly find your plugin to be very helpful for builds. When running the dev server I do notice the following pattern: The server is started, page loads and it refreshes again because of a new dependency being found.
> 
> ```
> 12:37:44 PM [vite] new dependencies found: @material-ui/core/esm/CircularProgress, @material-ui/core/esm/Box, updating...
> 12:37:45 PM [vite] ✨ dependencies updated, reloading page...
> 12:37:47 PM [vite] new dependencies found: @material-ui/core/esm/Grid, updating...
> 12:37:48 PM [vite] ✨ dependencies updated, reloading page...
> 12:37:53 PM [vite] new dependencies found: @material-ui/core/esm/Fade, @material-ui/core/esm/Slide, updating...
> 12:37:55 PM [vite] ✨ dependencies updated, reloading page...
> 12:37:58 PM [vite] new dependencies found: @material-ui/core/esm/useMediaQuery, updating...
> 12:37:59 PM [vite] ✨ dependencies updated, reloading page...
> 12:38:04 PM [vite] new dependencies found: @material-ui/core/esm/IconButton, updating...
> 12:38:05 PM [vite] ✨ dependencies updated, reloading page...
> 12:38:08 PM [vite] new dependencies found: @material-ui/core/esm/Button, updating...
> 12:38:09 PM [vite] ✨ dependencies updated, reloading page...
> ```
> 
> I have in my config the following
> 
> ```ts
> import tsconfigPaths from 'vite-tsconfig-paths';
> ...
>     pluginImport({
>       libraryName: '@material-ui/core',
>       libraryDirectory: 'esm',
>       camel2DashComponentName: false,
>     }),
>     pluginImport({
>       libraryName: 'lodash-es',
>       libraryDirectory: '',
>       camel2DashComponentName: false,
>     }),
> ```

You can try [vite-plugin-importus](https://github.com/Geocld/vite-plugin-importus), `vite-plugin-importus` use [es-module-lexer](https://github.com/guybedford/es-module-lexer) to transform codes internally so it has higher performance.
